export const builders = [
  {
    name: 'Elliott Homes',
    tier: 'priority',
    segment: 'Local / regional',
    score: 94,
    cities: ['Elk Grove', 'Rancho Cordova', 'El Dorado Hills', 'Galt', 'Lincoln'],
    communities: 'Elliott Springs, Rio Del Oro, Saratoga, Elliott Ranch and Turkey Creek Estates',
    lender: 'No captive lender identified on reviewed builder pages',
    route: '866-984-1300 · Folsom office / official inquiry',
    angle: 'Lead with a second-look pilot, jumbo and custom-buyer support, and difficult-income rescue.',
    source: 'https://www.elliotthomes.com/communities/california/sacramento',
    contact: 'https://www.elliotthomes.com/contact-us',
  },
  {
    name: 'JMC Homes',
    tier: 'priority',
    segment: 'Local',
    score: 92,
    cities: ['Roseville', 'Rocklin', 'Placer One'],
    communities: 'Parkfield, Bridgefield, Highline Village, Overland Village and Tribute Pointe',
    lender: 'Site says JMC is not acting as or representing a mortgage lender',
    route: '916-782-8879 · 1430 Blue Oaks Blvd., Roseville',
    angle: 'Ask for the sales leader responsible for financing escalations; offer jumbo and fallout rescue.',
    source: 'https://www.jmchomes.com/communities',
    contact: 'https://www.jmchomes.com/',
  },
  {
    name: 'Blue Mountain Communities',
    tier: 'priority',
    segment: 'Regional',
    score: 89,
    cities: ['Rescue', 'Granite Bay', 'Galt'],
    communities: 'Oakhaven, The Glen and Parlin Oaks',
    lender: 'Preferred-lenders page exists; verify current arrangement',
    route: '707-564-5245 · Oakhaven@bluemountaincommunities.com',
    angle: 'Jumbo, acreage, bridge and nonstandard-income scenarios.',
    source: 'https://bluemountaincommunities.com/communities/oakhaven-in-rescue/',
    contact: 'https://bluemountaincommunities.com/contact/',
  },
  {
    name: 'Riverland Homes',
    tier: 'priority',
    segment: 'Local',
    score: 87,
    cities: ['Elk Grove', 'Galt', 'Sacramento'],
    communities: 'Tegan Estates, Dry Creek Oaks and Pinecrest Village',
    lender: 'No captive lender verified in reviewed sources',
    route: '916-347-4972 sales · 916-850-0536 office',
    angle: 'Pitch a narrow 30-day backup-financing pilot with weekend coverage.',
    source: 'https://www.riverlandhomes.com/our-communities',
    contact: 'https://www.riverlandhomes.com/contact-us',
  },
  {
    name: 'BlackPine Communities',
    tier: 'priority',
    segment: 'Local developer',
    score: 86,
    cities: ['Sacramento', 'Midtown', 'El Dorado Hills'],
    communities: 'Four40 West available; T20 Lofts and Sienna Ridge listed as coming soon',
    lender: 'No captive lender verified in reviewed sources',
    route: '916-497-0900 · contact@blackpinecommunities.com',
    angle: 'Enter early—ask who is determining financing resources before new projects open.',
    source: 'https://www.blackpinecommunities.com/contact',
    contact: 'https://www.blackpinecommunities.com/contact',
  },
  {
    name: 'Woodside Homes',
    tier: 'growth',
    segment: 'Regional',
    score: 82,
    cities: ['Folsom', 'Granite Bay', 'Lincoln', 'Rancho Cordova', 'Roseville'],
    communities: 'The Trails, The Park at Granite Bay, Freedom at Liberty, Cypress and Winding Creek communities',
    lender: 'HomeAmerican Mortgage advertised as a partner route',
    route: 'Northern California contact / community inquiry',
    angle: 'Overflow, denied borrowers, product gaps and independently sourced buyers.',
    source: 'https://www.woodsidehomes.com/findmyhome/northern-california',
    contact: 'https://www.woodsidehomes.com/contact-us',
  },
  {
    name: 'KB Home',
    tier: 'growth',
    segment: 'National',
    score: 80,
    cities: ['Roseville', 'Lincoln', 'Placer One', 'Elk Grove', 'Folsom', 'Sacramento'],
    communities: 'Archer Estates, Aurora Heights and five Placer One communities',
    lender: 'KBHS Home Loans advertised',
    route: '916-272-1325 · Sacramento Online Sales Counselor',
    angle: 'First-time-buyer, FHA/VA and second-look opportunities; do not pitch lender displacement.',
    source: 'https://www.kbhome.com/new-homes-sacramento',
    contact: 'https://www.kbhome.com/new-homes-sacramento',
  },
  {
    name: 'Taylor Morrison',
    tier: 'growth',
    segment: 'National',
    score: 79,
    cities: ['Sacramento', 'Roseville', 'Elk Grove', 'Lincoln'],
    communities: 'Wildhawk North, Willow Vista, Winding Creek, Solaire, Madeira Ranch and Turkey Creek',
    lender: 'Taylor Morrison Home Funding advertised',
    route: 'Sacramento market inquiry / community sales pages',
    angle: 'Rescue and buyer-source strategy around a well-established affiliate.',
    source: 'https://www.taylormorrison.com/ca/sacramento',
    contact: 'https://www.taylormorrison.com/ca/sacramento',
  },
  {
    name: 'Meritage Homes',
    tier: 'growth',
    segment: 'National',
    score: 78,
    cities: ['Rancho Cordova', 'Sacramento', 'Lincoln', 'Galt', 'Elk Grove'],
    communities: 'East Village, Dockside, Legacy at Liberty, Liberty Ranch and Vinterra',
    lender: 'MTH Mortgage advertised',
    route: '916-631-1313 · Sacramento Sales Team',
    angle: 'Ask for a one-community pilot focused on affiliate fallout and weekend response.',
    source: 'https://www.meritagehomes.com/state/ca/sacramento',
    contact: 'https://www.meritagehomes.com/state/ca/sacramento',
  },
  {
    name: 'Toll Brothers',
    tier: 'growth',
    segment: 'National / luxury',
    score: 77,
    cities: ['Folsom', 'El Dorado Hills', 'Rocklin', 'Bickford Ranch'],
    communities: 'Folsom Ranch, Summit Estates, Bickford and Vista Oaks',
    lender: 'Toll Brothers Mortgage Company advertised',
    route: 'Official Talk to an Expert / contact route',
    angle: 'Jumbo, complex income and second opinions; affiliate displacement is unlikely.',
    source: 'https://www.tollbrothers.com/luxury-homes/California',
    contact: 'https://www.tollbrothers.com/contact',
  },
  {
    name: 'Shea Homes / Trilogy',
    tier: 'growth',
    segment: 'National / 55+',
    score: 75,
    cities: ['Bickford Ranch'],
    communities: 'Trilogy Bickford, actively selling 55+ community with quick move-ins',
    lender: 'Shea Mortgage directly advertised',
    route: '866-696-7432 · market interest / tour form',
    angle: 'Second opinions, retiree income structures and independently sourced buyers.',
    source: 'https://www.sheahomes.com/new-homes/california/sacramento/',
    contact: 'https://www.sheahomes.com/new-homes/california/sacramento/',
  },
  {
    name: 'Century Communities',
    tier: 'growth',
    segment: 'National',
    score: 74,
    cities: ['Sacramento', 'Lincoln', 'Davis'],
    communities: 'Official Northern California page exposes Sacramento, Lincoln and Davis searches',
    lender: 'Inspire Home Loans advertised',
    route: '925-234-9015 · Northern California Online Sales Coordinator',
    angle: 'Entry-level and first-time-buyer overflow; verify current lots before outreach.',
    source: 'https://www.centurycommunities.com/find-your-new-home/california/northern-california-metro/',
    contact: 'https://www.centurycommunities.com/find-your-new-home/california/northern-california-metro/',
  },
  {
    name: 'Lennar',
    tier: 'strategic',
    segment: 'National',
    score: 70,
    cities: ['Greater Sacramento'],
    communities: 'Live metro inventory changes frequently; use official community search',
    lender: 'Lennar Mortgage advertised',
    route: 'Community-specific Request Info / sales route',
    angle: 'High-volume long game: outside-lender choice, decline rescue and buyers you bring.',
    source: 'https://www.lennar.com/new-homes/california/sacramento',
    contact: 'https://www.lennar.com/new-homes/california/sacramento',
  },
  {
    name: 'D.R. Horton',
    tier: 'strategic',
    segment: 'National',
    score: 68,
    cities: ['Sacramento division'],
    communities: 'Division verified; live inventory should be confirmed by phone or current search',
    lender: 'DHI Mortgage advertised',
    route: 'Official Sacramento division page',
    angle: 'Do not seek first-position displacement; target fallout and sourced buyers.',
    source: 'https://www.drhorton.com/california/sacramento',
    contact: 'https://www.drhorton.com/california/sacramento',
  },
];

export const sources = [
  ['North State BIA public directory', 'https://www.northstatebia.org/public-directory-/', 'Builder and developer universe'],
  ['North State BIA membership', 'https://www.northstatebia.org/membership-information', 'Industry access'],
  ['Speed Networking With Builders', 'https://www.northstatebia.org/events/speed-networking-with-builders-', 'September 17, 2026'],
  ['Builders & Brews Sacramento', 'https://www.northstatebia.org/events/builders-and-brews-sacramento-2026', 'September 10, 2026'],
  ['Placer Builder/Developer Council', 'https://www.northstatebia.org/events/placer-builder-developer-council-meeting-aug26', 'August 19, 2026'],
  ['El Dorado Builder/Developer Council', 'https://www.northstatebia.org/events/el-dorado-builder-developer-council-meeting-aug26', 'August 26, 2026'],
  ['CFPB Regulation X §1024.14', 'https://www.consumerfinance.gov/rules-policy/regulations/1024/14/', 'Kickbacks and unearned fees'],
  ['CFPB Regulation X §1024.15', 'https://www.consumerfinance.gov/rules-policy/regulations/1024/15/', 'Affiliated business arrangements'],
  ['CFPB RESPA Section 8 FAQs', 'https://www.consumerfinance.gov/compliance/compliance-resources/mortgage-resources/real-estate-settlement-procedures-act/real-estate-settlement-procedures-act-faqs/', 'Marketing and referrals'],
  ['California DRE Public Reports', 'https://www.dre.ca.gov/Developers/PublicReports.html', 'Subdivision diligence'],
  ['NAF loan types', 'https://www.newamericanfunding.com/loan-types/', 'Public product menu'],
  ['NAF One-Time Close', 'https://www.newamericanfunding.com/loan-types/one-time-close-construction-loan/', 'Construction lending'],
  ['NAF real-estate partners', 'https://www.newamericanfunding.com/real-estate-agents/', 'Partner tools and public claims'],
];
